### ISSUE TITLE
[main] --: /tmp/.WJf2lg: /bin/sh: bad interpreter: Text file busy

### ISSUE THREAD

**Issue by weirdbricks** [marghidanu/werk#21]
Hi,

I am trying to test Werk out for the first time and I'm running into the following error. 

Here's how to repro:

```
docker run --name werk_test -dt centos:7 bash
docker exec -it werk_test bash
curl -LO https://github.com/marghidanu/werk/releases/download/0.7.3/werk-linux-x64
chmod +x werk-linux-x64
```

Now I add a very basic werk.yml:

```
version: "1"

description: "Manage Werk with Werk"

jobs:
  main:
    description: "sleep"
    executor: local
    commands:
      - sleep 1
```

Planning works:

```
./werk-linux-x64 plan
┌──────────────────────────────────┐
│             Stage 0              │
├────────┬─────────────┬───────────┤
│  Name  │ Description │ Can fail? │
├────────┼─────────────┼───────────┤
│  main  │ sleep       │    No     │
└────────┴─────────────┴───────────┘
```

But not running: 

```
./werk-linux-x64 run
[main] --: /tmp/.et15hF: /bin/sh: bad interpreter: Text file busy
```

Any ideas or am I doing something wrong? 

Thanks!
