### ISSUE TITLE
Rename "default" job to "main" in the Init subcommand

### ISSUE THREAD

**Issue by marghidanu** [marghidanu/werk#3]
The "init" subcommand generates the base configuration with the wrong job name:

```
---
version: "1"
description: Lorem ipsum dolor sic amet ...
variables: {}
jobs:
  default:
    description: Default job
    variables: {}
    commands:
    - echo "Hello world!"
    needs: []
    can_fail: false
    silent: false
```
